server:
  port: 8090
spring:
  datasource:
    name: test
    url: jdbc:mysql://127.0.0.1:3306/cmnt_ysc?useUnicode=true&characterEncoding=utf8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  mvc:
    static-path-pattern: /**  #路径就是static
  resources:
    static-locations: classpath:/static/   #classpath等于static同级

mybatis:
  mapper-locations: classpath:mybatis/*.xml
  type-aliases-package: com.example/**/*

